Add solution for CounterButton
js-tasks-ru/vue-20210119_eugene5 pull request #4
Opened 2021-02-02 17:10 UTC by mimoni

2021-02-02 17:16 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен иметь count 0 по умолчанию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2021-02-03 10:31 UTC, ShGKme requested changes
Требуется оставить только параметр count и событие increment, а также либо синхронизировать локальное состояние с входным параметром (используя watch), либо не использовать локальное состояние `currentCount`.

2021-02-03 10:31 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    },
Параметр `value` не требуется по условию задачи. 
Хотя модель компонента по умолчанию работает на `value+input`, она определяется свойством `model` при описании компонента: https://vuejs.org/v2/api/#model

2021-02-03 10:31 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +      this.$emit('input', this.currentCount);
Аналогично параметру `value`, событие `input` не требовалось.

2021-02-03 10:31 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
Задачу можно решать, сохраняя значение в локальное состояние. Но в этом случае возникает проблема: `currentCount` только инициализируется со значением входного параметра на момент инициализации данных компонента при инициализации компонента, но никакой связи между входным параметром и свойством `currentCount` нет. Например, если родитель изменит значение входного параметра, то CounterButton об этом не знает. Требуется его самостоятельно отслеживать и поддерживать `currentCount` в актуальном состоянии.

Но в этой задаче не требовалось компоненту иметь локальное состояние, так как он работает всегда от значения входного параметра, а работу по обновлении значения перекладывает на родителя через событие.

Достаточно использовать входной параметр в качестве счётчика, а при необходимости увеличить значение просто порождать событие с новым значением (текущее значение + 1). Изменять при этом какое-либо значение не требуется, этим будет заниматься родитель (пользователь) компонента.

2021-02-03 19:12 UTC, ShGKme approved these changes
Принято 👍

2021-02-03 19:12 UTC, merged